#ifndef KINC_WL_FN
#define KINC_WL_FN(ret, name, args)
#endif

KINC_WL_FUN(void, wl_event_queue_destroy, (struct wl_event_queue * queue))
#if KINC_WL_CHECK_VERSION(1, 20, 0)
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_flags,
            (struct wl_proxy * proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, ...))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_array_flags,
            (struct wl_proxy * proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, uint32_t flags, union wl_argument *args))
#endif
KINC_WL_FUN(void, wl_proxy_marshal, (struct wl_proxy * p, uint32_t opcode, ...))
KINC_WL_FUN(void, wl_proxy_marshal_array, (struct wl_proxy * p, uint32_t opcode, union wl_argument *args))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_create, (struct wl_proxy * factory, const struct wl_interface *interface))
KINC_WL_FUN(void *, wl_proxy_create_wrapper, (void *proxy))
KINC_WL_FUN(void, wl_proxy_wrapper_destroy, (void *proxy_wrapper))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_constructor, (struct wl_proxy * proxy, uint32_t opcode, const struct wl_interface *interface, ...))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_constructor_versioned,
            (struct wl_proxy * proxy, uint32_t opcode, const struct wl_interface *interface, uint32_t version, ...))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_array_constructor,
            (struct wl_proxy * proxy, uint32_t opcode, union wl_argument *args, const struct wl_interface *interface))
KINC_WL_FUN(struct wl_proxy *, wl_proxy_marshal_array_constructor_versioned,
            (struct wl_proxy * proxy, uint32_t opcode, union wl_argument *args, const struct wl_interface *interface, uint32_t version))
KINC_WL_FUN(void, wl_proxy_destroy, (struct wl_proxy * proxy))
KINC_WL_FUN(int, wl_proxy_add_listener, (struct wl_proxy * proxy, void (**implementation)(void), void *data))
KINC_WL_FUN(const void *, wl_proxy_get_listener, (struct wl_proxy * proxy))
KINC_WL_FUN(int, wl_proxy_add_dispatcher, (struct wl_proxy * proxy, wl_dispatcher_func_t dispatcher_func, const void *dispatcher_data, void *data))
KINC_WL_FUN(void, wl_proxy_set_user_data, (struct wl_proxy * proxy, void *user_data))
KINC_WL_FUN(void *, wl_proxy_get_user_data, (struct wl_proxy * proxy))
KINC_WL_FUN(uint32_t, wl_proxy_get_version, (struct wl_proxy * proxy))
KINC_WL_FUN(uint32_t, wl_proxy_get_id, (struct wl_proxy * proxy))
KINC_WL_FUN(void, wl_proxy_set_tag, (struct wl_proxy * proxy, const char *const *tag))
KINC_WL_FUN(const char *const *, wl_proxy_get_tag, (struct wl_proxy * proxy))
KINC_WL_FUN(const char *, wl_proxy_get_class, (struct wl_proxy * proxy))
KINC_WL_FUN(void, wl_proxy_set_queue, (struct wl_proxy * proxy, struct wl_event_queue *queue))
KINC_WL_FUN(struct wl_display *, wl_display_connect, (const char *name))
KINC_WL_FUN(struct wl_display *, wl_display_connect_to_fd, (int fd))
KINC_WL_FUN(void, wl_display_disconnect, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_get_fd, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_dispatch, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_dispatch_queue, (struct wl_display * display, struct wl_event_queue *queue))
KINC_WL_FUN(int, wl_display_dispatch_queue_pending, (struct wl_display * display, struct wl_event_queue *queue))
KINC_WL_FUN(int, wl_display_dispatch_pending, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_get_error, (struct wl_display * display))
KINC_WL_FUN(uint32_t, wl_display_get_protocol_error, (struct wl_display * display, const struct wl_interface **interface, uint32_t *id))
KINC_WL_FUN(int, wl_display_flush, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_roundtrip_queue, (struct wl_display * display, struct wl_event_queue *queue))
KINC_WL_FUN(int, wl_display_roundtrip, (struct wl_display * display))
KINC_WL_FUN(struct wl_event_queue *, wl_display_create_queue, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_prepare_read_queue, (struct wl_display * display, struct wl_event_queue *queue))
KINC_WL_FUN(int, wl_display_prepare_read, (struct wl_display * display))
KINC_WL_FUN(void, wl_display_cancel_read, (struct wl_display * display))
KINC_WL_FUN(int, wl_display_read_events, (struct wl_display * display))
KINC_WL_FUN(void, wl_log_set_handler_client, (wl_log_func_t handler))
