#define KINC_IMPLEMENTATION_ROOT

#include "color.h"
#include "error.h"
#include "log.h"
#include "memory.h"
#include "string.h"
#include "system.h"
#include "window.h"
#include "http.h"
// #include "socket.h"
#include "filereader.h"
#include "filewriter.h"
#include "gamepad.h"
#include "keyboard.h"
#include "mouse.h"
#include "pen.h"
#include "surface.h"
#include "core.h"
#include "matrix.h"
#include "random.h"
#include "g5_pipeline.c.h"
#include "g5_buffer.c.h"
#include "g5.c.h"
